In [1]:
import numpy as np

In [2]:
mylist =[1,2,3]
type(mylist)

list

In [5]:
myarr=np.array(mylist)

In [4]:
type(np.array(mylist))


numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]


In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.array([[2,3,4],[5,6,7],[8,9,10]])


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [14]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [25]:
np.zeros((2,5))

NameError: name 'shape' is not defined

In [22]:
len(np.linspace(0,10,3))


3

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.rand(3)

array([0.70936474, 0.22940392, 0.58125627])

In [29]:
np.random.rand(5,2)


array([[0.60311613, 0.72719227],
       [0.54606269, 0.96787304],
       [0.3653871 , 0.21864127],
       [0.55104776, 0.26835994],
       [0.3076424 , 0.02740726]])

In [30]:
np.random.randn(5)

array([ 0.27134711, -0.16216671,  0.07480617, -0.23929165,  0.20739032])

In [31]:
np.random.randint(0,101,(2,2))

array([[73, 46],
       [ 7, 29]])

In [43]:
np.random.seed(42)
np.random.rand(5,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [40]:
np.random.rand(5,2)

array([[0.60754485, 0.17052412],
       [0.06505159, 0.94888554],
       [0.96563203, 0.80839735],
       [0.30461377, 0.09767211],
       [0.68423303, 0.44015249]])

In [34]:
np.random.rand(5,2)

array([[0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914]])

In [44]:
arr = np.arange(0,25)

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
randint = np.random.randint(0,101,10)

In [47]:
randint

array([21, 52,  1, 87, 29, 37,  1, 63, 59, 20])

In [49]:
randint.max()

87

In [50]:
randint.argmax()

3

In [51]:
randint[randint.argmax()]

87

In [53]:
randint.dtype

dtype('int32')

In [54]:
randint.shape

(10,)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr.shape


(25,)

In [57]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
arr.shape

(25,)